# Generated by Django 5.0.6 on 2024-06-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='expiry',
            field=models.CharField(default='2025-12-31', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='holder',
            field=models.CharField(default='holder', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.CharField(default='0000000000000000', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(default='visa', max_length=50),
        ),
    ]
