# Generated by Django 5.0.6 on 2024-06-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_user_user_email_remove_user_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiance_goal',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
