# Generated by Django 5.0.6 on 2024-06-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiance_goal',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fiance_goal',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fiance_goal',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
